name: Test on any Push event
on: [push, pull_request]
jobs:
  test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        class-filter: [Decorator, Strategy, Facade, Builder, AbstractFactory]
        os: [windows-2019, ubuntu-18.04, ubuntu-16.04, macos-10.15]
    name: '${{ matrix.class-filter }}, ${{ matrix.os }}'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
        name: Clone repository
      - uses: actions/setup-dotnet@1.4.0
        name: Install dotnet
        with:
          dotnet-version: '3.1.101'
      - run: dotnet test --filter FullyQualifiedName~${{ matrix.class-filter }}
        name: Run test
